### ISSUE TITLE
Error loading BAGEL model: name 'Qwen2Config' is not defined

### ISSUE THREAD

**Issue by spookandrey1** [neverbiasu/ComfyUI-BAGEL#7]
Error loading BAGEL model: name 'Qwen2Config' is not defined
!!! Exception during processing !!! name 'Qwen2Config' is not defined
Traceback (most recent call last):
  File "G:\ComfyUI_art\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_art\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_art\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ComfyUI_art\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_art\ComfyUI\custom_nodes\ComfyUI-BAGEL\node.py", line 342, in load_model
    raise e
  File "G:\ComfyUI_art\ComfyUI\custom_nodes\ComfyUI-BAGEL\node.py", line 259, in load_model
    llm_config = Qwen2Config.from_json_file(
                 ^^^^^^^^^^^
NameError: name 'Qwen2Config' is not defined

![Image](https://github.com/user-attachments/assets/edebdaa7-ee59-4423-9107-82518b4c42b5)

**Comment by neverbiasu** [comment]
ok, plz provide the more error of info before the traceback

**Comment by billybasass** [comment]
> I think the dependencies are not totally installed.

I am getting the same. 

![Image](https://github.com/user-attachments/assets/1d083a3c-9ac4-4506-84b5-c6b2a1901ae2)

**Comment by mike-rowley** [comment]
The pathing seems to be an issue however once the model is in the correct location you get the Qwen2Config error.

This is the entire output of the run from prompt to the end of execution

**got prompt
Error loading BAGEL model: name 'Qwen2Config' is not defined
!!! Exception during processing !!! name 'Qwen2Config' is not defined
Traceback (most recent call last):
  File "D:\ComfyUIPortable-Debug\ComfyUI\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUIPortable-Debug\ComfyUI\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUIPortable-Debug\ComfyUI\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUIPortable-Debug\ComfyUI\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUIPortable-Debug\ComfyUI\custom_nodes\comfyui-bagel\node.py", line 342, in load_model
    raise e
  File "D:\ComfyUIPortable-Debug\ComfyUI\custom_nodes\comfyui-bagel\node.py", line 259, in load_model
    llm_config = Qwen2Config.from_json_file(
                 ^^^^^^^^^^^
NameError: name 'Qwen2Config' is not defined

Prompt executed in 4.07 seconds**

**Comment by billybasass** [comment]
> The pathing seems to be an issue however once the model is in the correct location you get the Qwen2Config error.
> 
this problem is one in the same. Qwen2Config error is because of the 2 paths that are being joined to make the call and the paths are not correct so there is no definition found from the string.

**Comment by mike-rowley** [comment]
@billybasass That is not the issue, I changed line 226 as you suggested:
base_model_dir = os.path.join(os.getcwd(), "ComfyUI", "models", "bagel")

And moved the models and still get the error.  The issue is that the Qwen2Config is actually undefined at runtime, seems like that class is not being imported or instantiated correctly.  I don't know enough about the code to fix it unfortunately.

![Image](https://github.com/user-attachments/assets/236d4556-e533-4ca0-92b2-d26ce6ac3d27)

**Comment by guahunyo** [comment]
![Image](https://github.com/user-attachments/assets/f0143cd8-eb9f-4064-a33d-6b01e95c084c)    same error

**Comment by zhu-guli326** [comment]
我也遇到了，请问解决了吗

**Comment by Blender66Cat** [comment]
same trouble

**Comment by cr7Por** [comment]
Error importing BAGEL modules: No module named 'flash_attn'
guys, check this, we should make sure that flash_attn is installed

**Comment by mrcedar-git** [comment]
“Error loading BAGEL model: name 'Qwen2Config' is not defined”，我也遇到相同的问题。

**Comment by myprivacygithub** [comment]
Error loading BAGEL model: name 'Qwen2Config' is not defined
!!! Exception during processing !!! name 'Qwen2Config' is not defined
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-BAGEL\node.py", line 342, in load_model
    raise e
  File "D:\ComfyUI\custom_nodes\ComfyUI-BAGEL\node.py", line 259, in load_model
    llm_config = Qwen2Config.from_json_file(
                 ^^^^^^^^^^^
NameError: name 'Qwen2Config' is not defined

**Comment by alenhrp** [comment]
same trouble，too.

**Comment by Jesssssss123** [comment]
same trouble,help

**Comment by littleowl** [comment]
I was getting the same error. And indeed, as someone said above, this project requires flash attention.
After installing it yesterday (takes a long time to build the wheel) I got things to work. Though, since the dependencies in requirements.txt are fixed, a lot of other nodes quit working. Not sure which ones actually need the specific versions..

**Comment by Derapt** [comment]
I solved the issue by installing `flash-attn` and `triton-windows` via pip. The problem arose because Triton (a dependency) doesn't support Windows, but it's required for the project to work. Using the Windows-specific `triton-windows` package fixed this.

**Comment by spookandrey1** [comment]
> yes, I think the error came from the missing dependencies, I will change the import logic help us find which one gone

I reinstalled all dependencies and downloaded the models again, but the error remained.
pytorch version: 2.6.0+cu126
xformers version: 0.0.29.post2
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
ComfyUI version: 0.3.36

**Comment by HDANILO** [comment]
Hi, I was able to find the minimal steps to reproduce the issue, and it seems like the issue lies within these lines:

`flex_attention = torch.compile(flex_attention)`

the actual error is:
```

Error importing BAGEL modules: cannot import name 'check_supported_striding' from 'torch._inductor.kernel.mm_common' (/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/kernel/mm_common.py)
Please ensure BAGEL model files are properly installed.
Warn!: Traceback (most recent call last):
  File "/home/dragonrollstudio/docker_opt/comfyui/nodes.py", line 2131, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL/__init__.py", line 5, in <module>
    from .node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL/node.py", line 24, in <module>
    from inferencer import InterleaveInferencer
  File "/home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL/inferencer.py", line 17, in <module>
    from modeling.bagel.qwen2_navit import NaiveCache
  File "/home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL/modeling/__init__.py", line 4, in <module>
    from . import bagel, qwen2, siglip, autoencoder
  File "/home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL/modeling/bagel/__init__.py", line 5, in <module>
    from .bagel import BagelConfig, Bagel
  File "/home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL/modeling/bagel/bagel.py", line 22, in <module>
    from .qwen2_navit import NaiveCache
  File "/home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL/modeling/bagel/qwen2_navit.py", line 40, in <module>
    flex_attention = torch.compile(flex_attention)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/__init__.py", line 2572, in compile
    return torch._dynamo.optimize(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 944, in optimize
    return _optimize(rebuild_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 1019, in _optimize
    backend.get_compiler_config()
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/__init__.py", line 2350, in get_compiler_config
    from torch._inductor.compile_fx import get_patched_config_dict
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 101, in <module>
    from .fx_passes.joint_graph import joint_graph_passes
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 23, in <module>
    from ..pattern_matcher import (
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/pattern_matcher.py", line 79, in <module>
    from .lowering import fallback_node_due_to_unsupported_type
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/lowering.py", line 7027, in <module>
    import_submodule(kernel)
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_dynamo/utils.py", line 3412, in import_submodule
    importlib.import_module(f"{mod.__name__}.{filename[:-3]}")
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/kernel/mm_scaled_grouped.py", line 26, in <module>
    from .mm_common import (
ImportError: cannot import name 'check_supported_striding' from 'torch._inductor.kernel.mm_common' (/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/kernel/mm_common.py)

Warn!: Cannot import /home/dragonrollstudio/docker_opt/comfyui/custom_nodes/ComfyUI-BAGEL module for custom nodes: cannot import name 'check_supported_striding' from 'torch._inductor.kernel.mm_common' (/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/kernel/mm_common.py)
```

**Comment by yitao2020** [comment]
Is there any new progress in this issue now? Expect to be solved

**Comment by mliand** [comment]
same question ,qwen2 config not defined

**Comment by yang-0201** [comment]
+1

**Comment by tarunm14** [comment]
+1

**Comment by neverbiasu** [comment]
I suggest some problems come from `flash_attention`, but @spookandrey1 ur issue isn't, it probably came from the `torch.compile` mentioned by @HDANILO (thanks ur reproduction & debug). I create a PR #16 for it, plz copy the code for trying and feedback in that PR, thanks.

**Comment by yzzky** [comment]
> I just find the solution.
> 
> I reinstall the requiements.txt in the Bagel repo as bellow : decord==0.6.0 einops==0.8.1 huggingface_hub==0.29.1 matplotlib==3.7.0 numpy==1.24.4 opencv_python==4.7.0.72 pyarrow==11.0.0 PyYAML==6.0.2 Requests==2.32.3 safetensors==0.4.5 scipy==1.10.1 sentencepiece==0.1.99 torch==2.5.1 torchvision==0.20.1 transformers==4.49.0 flash_attn==2.5.8 accelerate>=0.34.0 wandb
> 
> then it worked.

This issue  was  caused by the import  failure  on  top of node.py .  so instaling the requirements.txt  in  bagel  repo  can help fix the import failure , and  then  it worked

**Comment by yitao2020** [comment]
> > I just find the solution.
> > I reinstall the requiements.txt in the Bagel repo as bellow : decord==0.6.0 einops==0.8.1 huggingface_hub==0.29.1 matplotlib==3.7.0 numpy==1.24.4 opencv_python==4.7.0.72 pyarrow==11.0.0 PyYAML==6.0.2 Requests==2.32.3 safetensors==0.4.5 scipy==1.10.1 sentencepiece==0.1.99 torch==2.5.1 torchvision==0.20.1 transformers==4.49.0 flash_attn==2.5.8 accelerate>=0.34.0 wandb
> > then it worked.
> 
> This issue was caused by the import failure on top of node.py . so instaling the requirements.txt in bagel repo can help fix the import failure , and then it worked


ERROR: Ignored the following yanked versions: 1.11.0, 1.14.0rc1
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement scipy==1.10.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.9.2, 1.9.3, 1.11.0rc1, 1.11.0rc2, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.13.0rc1, 1.13.0, 1.13.1, 1.14.0rc2, 1.14.0, 1.14.1, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.16.0rc1)
ERROR: No matching distribution found for scipy==1.10.1

I tried this and found that it was not found scipy==1.10.1

**Comment by neverbiasu** [comment]
Here's my environment
```
Total VRAM 24564 MB, total RAM 130761 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
accelerate 1.5.2 
scipy 1.10.1
transformers 4.52.3 
flash_attn 2.5.8
```
### `Qwen2Config` Error Summary

The core issue, "**`name 'Qwen2Config' is not defined`**," indicates that the Python environment fails to recognize the `Qwen2Config` class which is defined in `qwen2_navit.py`.

| **Cause** | **Description** | **Solution** |
| :-------- | :------------------------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Dependency Mismatches** | Incompatible or missing versions of key libraries, such as `transformers`, `torch`, and `flash_attn`, prevent `Qwen2Config` from being recognized. | **Strict Dependency Installation:** Reinstall all dependencies using the precise versions specified in the project's `requirements.txt`, e.g., `torch==2.5.1`, `transformers==4.49.0`, `flash_attn==2.5.8`, etc. |
| **`torch.compile` Conflicts** | The `torch.compile` optimization feature in `qwen2_navit.py` may cause module import failures, indirectly affecting `Qwen2Config` recognition. | **Apply Code Patches:** Modify `qwen2_navit.py` to use lazy compilation for `flex_attention` to avoid import-time errors. |

If your problem is different from the first person's issue in this thread, please open a new sub-issue. This will help us track and solve each problem more efficiently.
Also, please note that the first person's issue is not caused by an environment problem, so let's avoid mixing unrelated discussions about environment setup here. Thank you!

**Comment by davidspoon** [comment]
> https://huggingface.co/lldacing/flash-attention-windows-wheel/tree/main
> 
> https://hf-mirror.com/madbuda/triton-windows-builds/tree/main
> 
> **_install those wheel,solve it~_**

Solved the problem, thanks !

By the way, I had too a lot of problem with the version in the requirement file : I just removed the version for each library giving me problems ... not very professional but it was working (with the fact too that I download the last version of the repository). Hope that it can help others.

**Comment by HDANILO** [comment]
> I suggest some problems come from `flash_attention`, but [@spookandrey1](https://github.com/spookandrey1) ur issue isn't, it probably came from the `torch.compile` mentioned by [@HDANILO](https://github.com/HDANILO) (thanks ur reproduction & debug). I create a PR [#16](https://github.com/neverbiasu/ComfyUI-BAGEL/pull/16) for it, plz copy the code for trying and feedback in that PR, thanks.

Thanks for the quick response! I checked out the branch `q2cfg` and tried running, and I still got the same issue, yesterday I left my PC up and running getting flash-attn again(it can take even couple hours to compile the thing), but turns out the problem persisted even with that. `q2cfg` still didn't help. 

I still get

```
Error importing BAGEL modules: cannot import name 'check_supported_striding' from 'torch._inductor.kernel.mm_common' (/home/dragonrollstudio/miniconda3/lib/python3.12/site-packages/torch/_inductor/kernel/mm_common.py)
Please ensure BAGEL model files are properly installed and accessible in the Python path.
```

when running

**Comment by neverbiasu** [comment]
another alternative way which announced in BAGEL's issues https://github.com/ByteDance-Seed/Bagel/issues/87, using this wheel may help 50 series GPU users.
https://github.com/Dao-AILab/flash-attention/issues/1683

https://github.com/loscrossos/lib_flashattention/releases/tag/v2.7.4.post1_crossos00

**Comment by etobod** [comment]
I'm a Windows user, and had the same problem as mentioned by OP. 

What helped me is:

1. pip show flash-attn
2. ![Image](https://github.com/user-attachments/assets/210ebaaf-3dd6-4ddb-a094-2440c0eaa40f)
3. The flash-attn was not installed at all
4. pip install "https://github.com/loscrossos/lib_flashattention/releases/download/v2.7.4.post1_crossos00/flash_attn-2.7.4.post1-cp312-cp312-win_amd64.whl"
5. BUM, it works now, I hope it helps you

**Comment by myprivacygithub** [comment]
> I'm a Windows user, and had the same problem as mentioned by OP.
> 
> What helped me is:
> 
> 1. pip show flash-attn
> 
> ![Image](https://github.com/user-attachments/assets/210ebaaf-3dd6-4ddb-a094-2440c0eaa40f)
> 
> 3. The flash-attn was not installed at all
> 4. pip install "https://github.com/loscrossos/lib_flashattention/releases/download/v2.7.4.post1_crossos00/flash_attn-2.7.4.post1-cp312-cp312-win_amd64.whl"
> 
> ![Image](https://github.com/user-attachments/assets/01b04be0-eb8c-466c-8ea3-958c3041f1bc)
> 
> 6. BUM, it works now, I hope it helps you

Thanks, it works for me now.
